fragment PageParts on Page {
  __typename
  title
  hero {
    __typename
    slogan
    firstName
    lastName
    description
  }
  evolution {
    __typename
    period
    title
    tagline
    description
  }
  skills {
    __typename
    category
    items
    level
  }
}

fragment ProjectParts on Project {
  __typename
  title
  url
  desc
  stack
}
