export const themeClasses = {
  pageShell: 'bg-[color:var(--bg-color)] text-[color:var(--text-color)]',
  textSoft: 'text-[color:var(--text-muted)]',
  sectionBorder: 'border-[color:var(--border-subtle)]',
  container: 'max-w-6xl mx-auto px-3 sm:px-4 lg:px-0',
  sectionSpacing: 'space-y-16 sm:space-y-20 lg:space-y-24',
  sectionPadding: 'py-8 sm:py-10 lg:py-12',
  textBase: 'text-sm sm:text-base lg:text-lg',
  textSmall: 'text-xs sm:text-sm',
  textLarge: 'text-lg sm:text-xl lg:text-2xl',
  textXLarge: 'text-2xl sm:text-3xl lg:text-4xl',
  textXXLarge: 'text-3xl sm:text-4xl lg:text-5xl',
  touchTarget: 'min-h-[44px] min-w-[44px]',
  buttonBase: 'px-3 sm:px-4 py-2 sm:py-3',
  inputBase: 'min-h-[44px] px-3 sm:px-4 py-2 sm:py-3',
  gapSm: 'gap-3 sm:gap-4',
  gapMd: 'gap-4 sm:gap-5 lg:gap-6',
  gapLg: 'gap-5 sm:gap-6 lg:gap-7',
  gridSm: 'grid-cols-1 sm:grid-cols-2',
  gridMd: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3',
  gridLg: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4',
  gridXl: 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5',
};
