/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: components\astryx\portfolioTheme.ts
 * Command: astryx theme build components\astryx\portfolioTheme.ts --out components\astryx\portfolioTheme.css
 * Generated: 2026-07-20T13:54:09.230Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
