/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: components\astryx\portfolioTheme.ts
 * Command: astryx theme build components\astryx\portfolioTheme.ts --out components\astryx\portfolioTheme.css
 * Generated: 2026-07-20T13:54:09.231Z
 */

/// <reference path="./munverricht-portfolio.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const munverrichtPortfolioTheme: DefinedTheme;
